[package]
name = "est_core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.*"
icu_properties = "1.5.1"
serde = { version = "1", features = ["derive"] }
slotmap = "1"
smallvec = "1"
thiserror = "2"
url = "2"
winnow = "0.7.6"
