default = "search"

[[engines]]
id = "search"
type = "ortho"
default = "google"
script = "han"
to = "bing_cn"

[[engines]]
id = "google"
type = "cloze"
shorthand = "g"
template = "https://google.com/search?q={}"

[[engines]]
id = "bing"
type = "ortho"
shorthand = "b"
default = "bing_global"
script = "han"
to = "bing_cn"

[[engines]]
id = "bing_global"
type = "cloze"
template = "https://www.bing.com/search?q={}"

[[engines]]
id = "bing_cn"
type = "cloze"
template = "https://cn.bing.com/search?q={}"

[[engines]]
id = "duckduckgo"
type = "cloze"
shorthand = ["d", "ddg"]
template = "https://duckduckgo.com/?q={}"

[[engines]]
id = "baidu"
type = "cloze"
shorthand = ["bd", "百度"]
template = "https://www.baidu.com/s?wd={}"
