name: Build and Dockerize Web

on:
  push:
    branches:
      - main
      - 'ci-all-*'
      - 'ci-web-*'
  workflow_dispatch:

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/est_web

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Bun build
        run: |
          cd packages/est_web
          bun install
          bun run build
          cd .output
          bun install --production --cwd server

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./packages/est_web/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}